/**
 * Returns the dashboard's full HTML. Deliberately dependency-free (no CDN
 * libraries) — everything is inline CSS/SVG/vanilla JS, so the page loads
 * fast and never breaks because some third-party script changed. Data comes
 * in via google.script.run calls to getDashboardData_/getSheetRows_ in
 * Dashboard.gs, so the page is always reading the live sheet.
 */
function renderDashboardHtml_() {
  return '<!doctype html><html><head><base target="_top">' +
    '<meta charset="utf-8">' +
    '<style>' + DASHBOARD_CSS_ + '</style>' +
    '</head><body>' + DASHBOARD_BODY_ + '<script>' + DASHBOARD_JS_ + '</script></body></html>';
}

var DASHBOARD_CSS_ = [
  ':root{',
  '  --ink:#14181D; --paper:#F3F4F2; --panel:#FFFFFF; --line:rgba(20,24,29,.12); --muted:#5B6570;',
  '  --accent:#B5651D; --accent-soft:#F3E4CD; --good:#2F6B4C; --good-soft:#D9EBE0; --risk:#A23F30; --risk-soft:#F4DCD5;',
  '  --mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;',
  '  --sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;',
  '}',
  '@media (prefers-color-scheme: dark){:root{',
  '  --ink:#ECEEEC; --paper:#14171A; --panel:#1C2024; --line:rgba(236,238,236,.14); --muted:#9AA3A8;',
  '  --accent:#E0954A; --accent-soft:#2E2314; --good:#6FBE95; --good-soft:#17281F; --risk:#E17A66; --risk-soft:#301A15;',
  '}}',
  '*{box-sizing:border-box;}',
  'body{margin:0;background:var(--paper);color:var(--ink);font-family:var(--sans);font-size:14px;line-height:1.5;}',
  '.wrap{max-width:1160px;margin:0 auto;padding:20px 20px 64px;}',
  'header{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:20px;flex-wrap:wrap;}',
  'header h1{font-size:19px;margin:0;}',
  '#lastUpdated{font-family:var(--mono);font-size:11.5px;color:var(--muted);}',
  'button{font:inherit;background:var(--panel);color:var(--ink);border:1px solid var(--line);border-radius:7px;padding:7px 14px;cursor:pointer;}',
  'button:hover{border-color:var(--accent);}',
  '.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin-bottom:20px;}',
  '.tile{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:14px 16px;}',
  '.tile .k{font-family:var(--mono);font-size:10.5px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted);margin-bottom:6px;}',
  '.tile .v{font-family:var(--mono);font-size:26px;font-variant-numeric:tabular-nums;}',
  '.tile .v.risk{color:var(--risk);} .tile .v.good{color:var(--good);}',
  '.panel{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:16px 18px;margin-bottom:20px;}',
  '.panel h2{font-size:14px;margin:0 0 14px;}',
  '.cols{display:grid;grid-template-columns:1fr 1fr;gap:20px;}',
  '@media (max-width:760px){.cols{grid-template-columns:1fr;}}',
  '.funnelRow{display:grid;grid-template-columns:110px 1fr 40px;gap:10px;align-items:center;margin-bottom:8px;font-size:13px;}',
  '.funnelRow .bar{background:var(--accent-soft);border-radius:5px;height:16px;position:relative;overflow:hidden;}',
  '.funnelRow .bar .fill{background:var(--accent);height:100%;border-radius:5px;}',
  '.funnelRow .n{font-family:var(--mono);text-align:right;font-variant-numeric:tabular-nums;}',
  '.barRow{display:grid;grid-template-columns:120px 1fr 34px;gap:8px;align-items:center;margin-bottom:7px;font-size:12.5px;}',
  '.barRow .bar{background:var(--line);border-radius:5px;height:12px;overflow:hidden;}',
  '.barRow .fill{height:100%;border-radius:5px;background:var(--accent);}',
  '.barRow .fill.good{background:var(--good);} .barRow .fill.risk{background:var(--risk);}',
  '.senderCard{border:1px solid var(--line);border-radius:8px;padding:10px 12px;margin-bottom:8px;}',
  '.senderCard .top{display:flex;justify-content:space-between;font-family:var(--mono);font-size:12px;margin-bottom:6px;}',
  'ul.feed{list-style:none;margin:0;padding:0;max-height:340px;overflow-y:auto;display:flex;flex-direction:column;gap:8px;}',
  'ul.feed li{border-bottom:1px solid var(--line);padding-bottom:8px;font-size:12.5px;}',
  'ul.feed li .tag{font-family:var(--mono);font-size:10px;text-transform:uppercase;padding:1px 6px;border-radius:4px;background:var(--accent-soft);color:var(--accent);margin-right:6px;}',
  'ul.feed li .tag.interested{background:var(--good-soft);color:var(--good);}',
  'ul.feed li .tag.unsubscribe,ul.feed li .tag.not_interested{background:var(--risk-soft);color:var(--risk);}',
  'ul.feed li .when{float:right;font-family:var(--mono);font-size:10.5px;color:var(--muted);}',
  '.errorRow{border-left:3px solid var(--risk);background:var(--risk-soft);padding:6px 10px;border-radius:4px;margin-bottom:6px;font-size:12px;}',
  '.tableWrap{overflow-x:auto;border:1px solid var(--line);border-radius:8px;}',
  'table{border-collapse:collapse;width:100%;font-size:12px;min-width:600px;}',
  'th,td{padding:6px 10px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap;max-width:260px;overflow:hidden;text-overflow:ellipsis;}',
  'thead th{background:var(--accent-soft);font-family:var(--mono);font-size:10.5px;text-transform:uppercase;position:sticky;top:0;}',
  'select,input{font:inherit;padding:6px 10px;border-radius:7px;border:1px solid var(--line);background:var(--panel);color:var(--ink);}',
  '.empty{color:var(--muted);font-size:12.5px;padding:8px 0;}',
  '.badge{font-family:var(--mono);font-size:11px;padding:3px 9px;border-radius:20px;font-weight:600;}',
  '.badge.on{background:var(--good-soft);color:var(--good);} .badge.off{background:var(--risk-soft);color:var(--risk);}',
  '.controlRow{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:14px;}',
  'button.primary{background:var(--good);color:#fff;border-color:var(--good);}',
  'button.danger{color:var(--risk);border-color:var(--risk);}',
  'button:disabled{opacity:.5;cursor:default;}',
  '.stageGrid{display:flex;flex-wrap:wrap;gap:8px;}',
  '.msgLine{font-family:var(--mono);font-size:11.5px;color:var(--muted);margin-top:8px;min-height:14px;}',
  '.targetsWrap{overflow-x:auto;}',
  'table.targets{border-collapse:collapse;width:100%;font-size:12.5px;}',
  'table.targets th,table.targets td{padding:6px 8px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap;}',
  'table.targets thead th{font-family:var(--mono);font-size:10px;text-transform:uppercase;color:var(--muted);}',
  'table.targets tr.disabled{opacity:.45;}',
  '.smallBtn{padding:3px 9px;font-size:11.5px;}',
  '.addForm{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px;align-items:center;}',
  '.addForm input{flex:1;min-width:140px;}',
  '.draftCard{border:1px solid var(--line);border-radius:8px;padding:12px 14px;margin-bottom:10px;}',
  '.draftCard .subj{font-weight:600;margin-bottom:4px;}',
  '.draftCard .to{font-family:var(--mono);font-size:11px;color:var(--muted);margin-bottom:8px;}',
  '.draftCard .body{white-space:pre-wrap;font-size:12.5px;background:var(--paper);border-radius:6px;padding:10px;margin-bottom:10px;max-height:160px;overflow-y:auto;}',
  '.draftCard .actions{display:flex;gap:8px;}'
].join('\n');

var DASHBOARD_BODY_ = [
  '<div class="wrap">',
  '  <header>',
  '    <h1>Lead-Gen Autopilot — Dashboard</h1>',
  '    <div style="display:flex;align-items:center;gap:10px;">',
  '      <span id="lastUpdated">loading…</span>',
  '      <button onclick="loadAll()">Refresh</button>',
  '    </div>',
  '  </header>',
  '  <div class="panel">',
  '    <h2>Automation control</h2>',
  '    <div class="controlRow">',
  '      <span id="autoBadge" class="badge off">checking…</span>',
  '      <button class="primary" onclick="startAutomation()">Start automation</button>',
  '      <button class="danger" onclick="stopAutomation()">Stop automation</button>',
  '      <span id="autoMsg" class="msgLine" style="min-height:auto;margin-top:0;"></span>',
  '    </div>',
  '    <h2 style="margin-top:4px;">Run a stage right now</h2>',
  '    <div class="stageGrid">',
  '      <button onclick="runStage(\'sourceLeads\',this)">Source leads</button>',
  '      <button onclick="runStage(\'normalize\',this)">Normalize</button>',
  '      <button onclick="runStage(\'classify\',this)">Classify</button>',
  '      <button onclick="runStage(\'findContacts\',this)">Find contacts</button>',
  '      <button onclick="runStage(\'draftEmails\',this)">Draft emails</button>',
  '      <button onclick="runStage(\'queueApproved\',this)">Queue approved</button>',
  '      <button class="danger" onclick="runStage(\'sendQueue\',this)">Send queue now</button>',
  '      <button onclick="runStage(\'checkReplies\',this)">Check replies</button>',
  '    </div>',
  '    <div class="msgLine" id="stageMsg"></div>',
  '  </div>',
  '  <div class="grid" id="tiles"></div>',
  '  <div class="panel"><h2>Pipeline funnel</h2><div id="funnel"></div></div>',
  '  <div class="panel">',
  '    <h2>Drafts awaiting your review</h2>',
  '    <div id="drafts"></div>',
  '  </div>',
  '  <div class="panel">',
  '    <h2>Lead-source targets</h2>',
  '    <div class="controlRow">',
  '      <button class="smallBtn" onclick="setAllTargets(true)">Enable all</button>',
  '      <button class="smallBtn" onclick="setAllTargets(false)">Disable all</button>',
  '      <span id="targetsMsg" class="msgLine" style="min-height:auto;margin-top:0;"></span>',
  '    </div>',
  '    <div class="targetsWrap"><table class="targets"><thead><tr>',
  '      <th>On</th><th>Category</th><th>OSM tag</th><th>Location</th><th>Last run</th><th>Found</th><th></th>',
  '    </tr></thead><tbody id="targetsBody"></tbody></table></div>',
  '    <div class="addForm">',
  '      <input id="newCategory" placeholder="Category, e.g. Coaching centre">',
  '      <input id="newTag" placeholder="osm_tag, e.g. amenity=driving_school">',
  '      <input id="newLocation" placeholder="Location, e.g. Nagpur, India">',
  '      <button class="primary" onclick="addTarget()">Add target</button>',
  '    </div>',
  '  </div>',
  '  <div class="cols">',
  '    <div class="panel"><h2>Replies by category</h2><div id="replyBreakdown"></div></div>',
  '    <div class="panel"><h2>Sender performance (today / daily cap)</h2><div id="senderStats"></div></div>',
  '  </div>',
  '  <div class="cols">',
  '    <div class="panel"><h2>Recent activity</h2><ul class="feed" id="activity"></ul></div>',
  '    <div class="panel"><h2>Recent errors</h2><div id="errors"></div></div>',
  '  </div>',
  '  <div class="panel">',
  '    <h2>Raw data explorer</h2>',
  '    <div style="margin-bottom:12px;"><select id="sheetPicker" onchange="loadSheet(this.value)"></select></div>',
  '    <div class="tableWrap"><table id="sheetTable"><thead><tr id="sheetHead"></tr></thead><tbody id="sheetBody"></tbody></table></div>',
  '  </div>',
  '</div>'
].join('\n');

var DASHBOARD_JS_ = [
  'function esc(s){ return String(s === undefined || s === null ? "" : s).replace(/&/g,"&amp;").replace(/</g,"&lt;"); }',
  '',
  'function loadAll(){',
  '  google.script.run.withSuccessHandler(render).withFailureHandler(renderError).getDashboardData();',
  '}',
  '',
  'function renderError(err){',
  '  document.getElementById("lastUpdated").textContent = "Error: " + (err && err.message ? err.message : err);',
  '}',
  '',
  'function tile(label, value, cls){',
  '  return \'<div class="tile"><div class="k">\' + esc(label) + \'</div><div class="v \' + (cls||"") + \'">\' + esc(value) + \'</div></div>\';',
  '}',
  '',
  'function render(data){',
  '  document.getElementById("lastUpdated").textContent = "Updated " + new Date(data.generatedAt).toLocaleString();',
  '',
  '  var interested = data.replyBreakdown.interested || 0;',
  '  document.getElementById("tiles").innerHTML = [',
  '    tile("Sourced", data.funnel[0].count),',
  '    tile("Sent", data.funnel[6].count),',
  '    tile("Replied", data.funnel[7].count),',
  '    tile("Interested", interested, "good"),',
  '    tile("Avg ICP fit", data.avgIcpScore),',
  '    tile("Suppressed", data.suppressionCount),',
  '    tile("Errors (24h)", data.errorCount24h, data.errorCount24h > 0 ? "risk" : "")',
  '  ].join("");',
  '',
  '  var maxFunnel = Math.max.apply(null, data.funnel.map(function(f){return f.count;})) || 1;',
  '  document.getElementById("funnel").innerHTML = data.funnel.map(function(f){',
  '    var pct = Math.round((f.count / maxFunnel) * 100);',
  '    return \'<div class="funnelRow"><span>\' + esc(f.stage) + \'</span><div class="bar"><div class="fill" style="width:\' + pct + \'%"></div></div><span class="n">\' + f.count + \'</span></div>\';',
  '  }).join("");',
  '',
  '  document.getElementById("replyBreakdown").innerHTML = renderBreakdown(data.replyBreakdown) || \'<div class="empty">No replies yet.</div>\';',
  '',
  '  document.getElementById("senderStats").innerHTML = data.senderStats.length ? data.senderStats.map(function(s){',
  '    var pct = s.dailyCap ? Math.min(100, Math.round((s.sentToday / s.dailyCap) * 100)) : 0;',
  '    return \'<div class="senderCard"><div class="top"><span>\' + esc(s.sender) + \'</span><span>\' + s.sentToday + \' / \' + s.dailyCap + \' today · \' + s.totalSent + \' all-time</span></div><div class="bar"><div class="fill\' + (pct>=100?" risk":"") + \'" style="width:\' + pct + \'%"></div></div></div>\';',
  '  }).join("") : \'<div class="empty">No SENDER_ACCOUNTS configured.</div>\';',
  '',
  '  document.getElementById("activity").innerHTML = data.recentActivity.length ? data.recentActivity.map(function(a){',
  '    var tagClass = a.type.indexOf("reply_") === 0 ? a.type.replace("reply_","") : "";',
  '    var label = a.type === "sent" ? "sent" : a.type.replace("reply_","reply: ");',
  '    return \'<li><span class="tag \' + tagClass + \'">\' + esc(label) + \'</span>\' + esc(a.detail) + \'<span class="when">\' + new Date(a.at).toLocaleString() + \'</span></li>\';',
  '  }).join("") : \'<li class="empty">Nothing sent or replied to yet.</li>\';',
  '',
  '  document.getElementById("errors").innerHTML = data.recentErrors.length ? data.recentErrors.map(function(e){',
  '    return \'<div class="errorRow"><b>\' + esc(e.function_name) + \'</b> — \' + esc(e.message) + \'<br><span style="opacity:.7">\' + new Date(e.timestamp).toLocaleString() + \'</span></div>\';',
  '  }).join("") : \'<div class="empty">No errors logged. Good sign.</div>\';',
  '}',
  '',
  'function renderBreakdown(obj){',
  '  var keys = Object.keys(obj);',
  '  if (!keys.length) return "";',
  '  var max = Math.max.apply(null, keys.map(function(k){return obj[k];}));',
  '  var cls = { interested: "good", not_interested: "risk", unsubscribe: "risk" };',
  '  return keys.sort(function(a,b){return obj[b]-obj[a];}).map(function(k){',
  '    var pct = Math.round((obj[k] / max) * 100);',
  '    return \'<div class="barRow"><span>\' + esc(k) + \'</span><div class="bar"><div class="fill \' + (cls[k]||"") + \'" style="width:\' + pct + \'%"></div></div><span>\' + obj[k] + \'</span></div>\';',
  '  }).join("");',
  '}',
  '',
  'function loadSheet(name){',
  '  google.script.run.withSuccessHandler(renderSheet).withFailureHandler(renderError).getSheetRows(name, 200);',
  '}',
  '',
  'function renderSheet(data){',
  '  var picker = document.getElementById("sheetPicker");',
  '  if (!picker.options.length) {',
  '    data.sheetNames.forEach(function(name){',
  '      var opt = document.createElement("option"); opt.value = name; opt.textContent = name; picker.appendChild(opt);',
  '    });',
  '    picker.value = "SentLog";',
  '  }',
  '  document.getElementById("sheetHead").innerHTML = data.header.map(function(h){return "<th>"+esc(h)+"</th>";}).join("");',
  '  document.getElementById("sheetBody").innerHTML = data.rows.length ? data.rows.map(function(row){',
  '    return "<tr>" + data.header.map(function(h){return "<td title=\\"" + esc(row[h]) + "\\">" + esc(row[h]) + "</td>";}).join("") + "</tr>";',
  '  }).join("") : \'<tr><td colspan="\' + data.header.length + \'" class="empty">No rows yet.</td></tr>\';',
  '}',
  '',
  'function loadAutomationStatus(){',
  '  google.script.run.withSuccessHandler(renderAutomationStatus).withFailureHandler(renderError).getAutomationStatus();',
  '}',
  '',
  'function renderAutomationStatus(data){',
  '  var badge = document.getElementById("autoBadge");',
  '  if (data.running) {',
  '    badge.className = "badge on";',
  '    badge.textContent = "Running — " + data.triggerCount + " trigger" + (data.triggerCount === 1 ? "" : "s") + " active";',
  '  } else {',
  '    badge.className = "badge off";',
  '    badge.textContent = "Stopped — nothing scheduled";',
  '  }',
  '}',
  '',
  'function startAutomation(){',
  '  setMsg("autoMsg", "Starting…");',
  '  google.script.run.withSuccessHandler(function(data){',
  '    renderAutomationStatus(data);',
  '    setMsg("autoMsg", "Started. Sourcing, classification, drafting, sending and reply-checking are all now on their timers.");',
  '  }).withFailureHandler(function(err){ setMsg("autoMsg", "Error: " + errText(err)); }).startAutomation();',
  '}',
  '',
  'function stopAutomation(){',
  '  setMsg("autoMsg", "Stopping…");',
  '  google.script.run.withSuccessHandler(function(data){',
  '    renderAutomationStatus(data);',
  '    setMsg("autoMsg", "Stopped. Nothing already queued or sent is affected — this only pauses future runs.");',
  '  }).withFailureHandler(function(err){ setMsg("autoMsg", "Error: " + errText(err)); }).stopAutomation();',
  '}',
  '',
  'var STAGE_LABELS_ = { sourceLeads:"Source leads", normalize:"Normalize", classify:"Classify", findContacts:"Find contacts", draftEmails:"Draft emails", queueApproved:"Queue approved", sendQueue:"Send queue", checkReplies:"Check replies" };',
  '',
  'function runStage(stage, btn){',
  '  if (stage === "sendQueue" && !confirm("This sends real emails to whatever is queued right now (still respecting daily caps and the send window). Continue?")) return;',
  '  btn.disabled = true;',
  '  setMsg("stageMsg", "Running " + STAGE_LABELS_[stage] + "…");',
  '  google.script.run.withSuccessHandler(function(result){',
  '    btn.disabled = false;',
  '    setMsg("stageMsg", STAGE_LABELS_[stage] + " done: " + JSON.stringify(result));',
  '    loadAll(); loadTargets(); loadDrafts();',
  '  }).withFailureHandler(function(err){',
  '    btn.disabled = false;',
  '    setMsg("stageMsg", STAGE_LABELS_[stage] + " failed: " + errText(err));',
  '  }).runPipelineStage(stage);',
  '}',
  '',
  'function loadTargets(){',
  '  google.script.run.withSuccessHandler(renderTargets).withFailureHandler(renderError).listSourceQueries();',
  '}',
  '',
  'function renderTargets(rows){',
  '  document.getElementById("targetsBody").innerHTML = rows.length ? rows.map(function(r){',
  '    var isOff = String(r.enabled).toUpperCase() === "FALSE";',
  '    var lastRun = r.last_run_at ? new Date(r.last_run_at).toLocaleString() : "never";',
  '    return \'<tr class="\' + (isOff?"disabled":"") + \'">\'',
  '      + \'<td><input type="checkbox" \' + (isOff?"":"checked") + \' onchange="toggleTarget(\' + r._rowNumber + \',this.checked)"></td>\'',
  '      + "<td>" + esc(r.category) + "</td>"',
  '      + "<td>" + esc(r.osm_tag) + "</td>"',
  '      + "<td>" + esc(r.location) + "</td>"',
  '      + "<td>" + esc(lastRun) + "</td>"',
  '      + "<td>" + esc(r.total_found || 0) + "</td>"',
  '      + \'<td><button class="smallBtn" onclick="runTargetNow(\' + r._rowNumber + \',this)">Run now</button> \'',
  '      + \'<button class="smallBtn danger" onclick="deleteTarget(\' + r._rowNumber + \')">Remove</button></td>\'',
  '      + "</tr>";',
  '  }).join("") : \'<tr><td colspan="7" class="empty">No targets configured yet — add one below.</td></tr>\';',
  '}',
  '',
  'function toggleTarget(rowNumber, enabled){',
  '  google.script.run.withSuccessHandler(renderTargets).withFailureHandler(function(err){ setMsg("targetsMsg", "Error: " + errText(err)); }).setSourceQueryEnabled(rowNumber, enabled);',
  '}',
  '',
  'function runTargetNow(rowNumber, btn){',
  '  btn.disabled = true;',
  '  setMsg("targetsMsg", "Running row " + rowNumber + "…");',
  '  google.script.run.withSuccessHandler(function(result){',
  '    btn.disabled = false;',
  '    setMsg("targetsMsg", "Done: " + JSON.stringify(result));',
  '    loadTargets(); loadAll();',
  '  }).withFailureHandler(function(err){',
  '    btn.disabled = false;',
  '    setMsg("targetsMsg", "Error: " + errText(err));',
  '  }).runSourceQueryNow(rowNumber);',
  '}',
  '',
  'function deleteTarget(rowNumber){',
  '  if (!confirm("Remove this target for good? (You can re-add it any time.)")) return;',
  '  google.script.run.withSuccessHandler(renderTargets).withFailureHandler(function(err){ setMsg("targetsMsg", "Error: " + errText(err)); }).deleteSourceQueryRow(rowNumber);',
  '}',
  '',
  'function setAllTargets(enabled){',
  '  google.script.run.withSuccessHandler(renderTargets).withFailureHandler(function(err){ setMsg("targetsMsg", "Error: " + errText(err)); }).setAllSourceQueriesEnabled(enabled);',
  '}',
  '',
  'function addTarget(){',
  '  var category = document.getElementById("newCategory").value.trim();',
  '  var tag = document.getElementById("newTag").value.trim();',
  '  var location = document.getElementById("newLocation").value.trim();',
  '  if (!category || !tag || !location) { setMsg("targetsMsg", "Fill in all three fields first."); return; }',
  '  google.script.run.withSuccessHandler(function(rows){',
  '    renderTargets(rows);',
  '    document.getElementById("newCategory").value = "";',
  '    document.getElementById("newTag").value = "";',
  '    document.getElementById("newLocation").value = "";',
  '    setMsg("targetsMsg", "Added.");',
  '  }).withFailureHandler(function(err){ setMsg("targetsMsg", "Error: " + errText(err)); }).addSourceQuery(category, tag, location);',
  '}',
  '',
  'function loadDrafts(){',
  '  google.script.run.withSuccessHandler(renderDrafts).withFailureHandler(renderError).listPendingDrafts();',
  '}',
  '',
  'function renderDrafts(rows){',
  '  document.getElementById("drafts").innerHTML = rows.length ? rows.map(function(d){',
  '    return \'<div class="draftCard">\'',
  '      + \'<div class="subj">\' + esc(d.subject) + "</div>"',
  '      + \'<div class="to">To: \' + esc(d.contact_email) + "</div>"',
  '      + \'<div class="body">\' + esc(d.body) + "</div>"',
  '      + \'<div class="actions">\'',
  '      + \'<button class="primary smallBtn" onclick="decideDraft(\' + d._rowNumber + \',\\\'approved\\\',this)">Approve</button>\'',
  '      + \'<button class="danger smallBtn" onclick="decideDraft(\' + d._rowNumber + \',\\\'rejected\\\',this)">Reject</button>\'',
  '      + "</div></div>";',
  '  }).join("") : \'<div class="empty">Nothing waiting on you right now.</div>\';',
  '}',
  '',
  'function decideDraft(rowNumber, status, btn){',
  '  btn.closest(".draftCard").style.opacity = ".4";',
  '  google.script.run.withSuccessHandler(renderDrafts).withFailureHandler(function(err){ alert("Error: " + errText(err)); loadDrafts(); }).setDraftStatus(rowNumber, status);',
  '}',
  '',
  'function setMsg(id, text){ document.getElementById(id).textContent = text; }',
  'function errText(err){ return err && err.message ? err.message : String(err); }',
  '',
  'loadAll();',
  'loadSheet("SentLog");',
  'loadAutomationStatus();',
  'loadTargets();',
  'loadDrafts();',
  'setInterval(loadAll, 60000);',
  'setInterval(loadAutomationStatus, 60000);'
].join('\n');
