/**
 * Returns the dashboard's full HTML. Deliberately dependency-free (no CDN
 * libraries) — everything is inline CSS/SVG/vanilla JS, so the page loads
 * fast and never breaks because some third-party script changed. Data comes
 * in via google.script.run calls to getDashboardData_/getSheetRows_ in
 * Dashboard.gs, so the page is always reading the live sheet.
 */
function renderDashboardHtml_() {
  return '<!doctype html><html><head><base target="_top">' +
    '<meta charset="utf-8">' +
    '<style>' + DASHBOARD_CSS_ + '</style>' +
    '</head><body>' + DASHBOARD_BODY_ + '<script>' + DASHBOARD_JS_ + '</script></body></html>';
}

var DASHBOARD_CSS_ = [
  ':root{',
  '  --ink:#14181D; --paper:#F3F4F2; --panel:#FFFFFF; --line:rgba(20,24,29,.12); --muted:#5B6570;',
  '  --accent:#B5651D; --accent-soft:#F3E4CD; --good:#2F6B4C; --good-soft:#D9EBE0; --risk:#A23F30; --risk-soft:#F4DCD5;',
  '  --mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;',
  '  --sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;',
  '}',
  '@media (prefers-color-scheme: dark){:root{',
  '  --ink:#ECEEEC; --paper:#14171A; --panel:#1C2024; --line:rgba(236,238,236,.14); --muted:#9AA3A8;',
  '  --accent:#E0954A; --accent-soft:#2E2314; --good:#6FBE95; --good-soft:#17281F; --risk:#E17A66; --risk-soft:#301A15;',
  '}}',
  '*{box-sizing:border-box;}',
  'body{margin:0;background:var(--paper);color:var(--ink);font-family:var(--sans);font-size:14px;line-height:1.5;}',
  '.wrap{max-width:1160px;margin:0 auto;padding:20px 20px 64px;}',
  'header{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:20px;flex-wrap:wrap;}',
  'header h1{font-size:19px;margin:0;}',
  '#lastUpdated{font-family:var(--mono);font-size:11.5px;color:var(--muted);}',
  'button{font:inherit;background:var(--panel);color:var(--ink);border:1px solid var(--line);border-radius:7px;padding:7px 14px;cursor:pointer;}',
  'button:hover{border-color:var(--accent);}',
  '.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin-bottom:20px;}',
  '.tile{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:14px 16px;}',
  '.tile .k{font-family:var(--mono);font-size:10.5px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted);margin-bottom:6px;}',
  '.tile .v{font-family:var(--mono);font-size:26px;font-variant-numeric:tabular-nums;}',
  '.tile .v.risk{color:var(--risk);} .tile .v.good{color:var(--good);}',
  '.panel{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:16px 18px;margin-bottom:20px;}',
  '.panel h2{font-size:14px;margin:0 0 14px;}',
  '.cols{display:grid;grid-template-columns:1fr 1fr;gap:20px;}',
  '@media (max-width:760px){.cols{grid-template-columns:1fr;}}',
  '.funnelRow{display:grid;grid-template-columns:110px 1fr 40px;gap:10px;align-items:center;margin-bottom:8px;font-size:13px;}',
  '.funnelRow .bar{background:var(--accent-soft);border-radius:5px;height:16px;position:relative;overflow:hidden;}',
  '.funnelRow .bar .fill{background:var(--accent);height:100%;border-radius:5px;}',
  '.funnelRow .n{font-family:var(--mono);text-align:right;font-variant-numeric:tabular-nums;}',
  '.barRow{display:grid;grid-template-columns:120px 1fr 34px;gap:8px;align-items:center;margin-bottom:7px;font-size:12.5px;}',
  '.barRow .bar{background:var(--line);border-radius:5px;height:12px;overflow:hidden;}',
  '.barRow .fill{height:100%;border-radius:5px;background:var(--accent);}',
  '.barRow .fill.good{background:var(--good);} .barRow .fill.risk{background:var(--risk);}',
  '.senderCard{border:1px solid var(--line);border-radius:8px;padding:10px 12px;margin-bottom:8px;}',
  '.senderCard .top{display:flex;justify-content:space-between;font-family:var(--mono);font-size:12px;margin-bottom:6px;}',
  'ul.feed{list-style:none;margin:0;padding:0;max-height:340px;overflow-y:auto;display:flex;flex-direction:column;gap:8px;}',
  'ul.feed li{border-bottom:1px solid var(--line);padding-bottom:8px;font-size:12.5px;}',
  'ul.feed li .tag{font-family:var(--mono);font-size:10px;text-transform:uppercase;padding:1px 6px;border-radius:4px;background:var(--accent-soft);color:var(--accent);margin-right:6px;}',
  'ul.feed li .tag.interested{background:var(--good-soft);color:var(--good);}',
  'ul.feed li .tag.unsubscribe,ul.feed li .tag.not_interested{background:var(--risk-soft);color:var(--risk);}',
  'ul.feed li .when{float:right;font-family:var(--mono);font-size:10.5px;color:var(--muted);}',
  '.errorRow{border-left:3px solid var(--risk);background:var(--risk-soft);padding:6px 10px;border-radius:4px;margin-bottom:6px;font-size:12px;}',
  '.tableWrap{overflow-x:auto;border:1px solid var(--line);border-radius:8px;}',
  'table{border-collapse:collapse;width:100%;font-size:12px;min-width:600px;}',
  'th,td{padding:6px 10px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap;max-width:260px;overflow:hidden;text-overflow:ellipsis;}',
  'thead th{background:var(--accent-soft);font-family:var(--mono);font-size:10.5px;text-transform:uppercase;position:sticky;top:0;}',
  'select{font:inherit;padding:6px 10px;border-radius:7px;border:1px solid var(--line);background:var(--panel);color:var(--ink);}',
  '.empty{color:var(--muted);font-size:12.5px;padding:8px 0;}'
].join('\n');

var DASHBOARD_BODY_ = [
  '<div class="wrap">',
  '  <header>',
  '    <h1>Lead-Gen Autopilot — Dashboard</h1>',
  '    <div style="display:flex;align-items:center;gap:10px;">',
  '      <span id="lastUpdated">loading…</span>',
  '      <button onclick="loadAll()">Refresh</button>',
  '    </div>',
  '  </header>',
  '  <div class="grid" id="tiles"></div>',
  '  <div class="panel"><h2>Pipeline funnel</h2><div id="funnel"></div></div>',
  '  <div class="cols">',
  '    <div class="panel"><h2>Replies by category</h2><div id="replyBreakdown"></div></div>',
  '    <div class="panel"><h2>Sender performance (today / daily cap)</h2><div id="senderStats"></div></div>',
  '  </div>',
  '  <div class="cols">',
  '    <div class="panel"><h2>Recent activity</h2><ul class="feed" id="activity"></ul></div>',
  '    <div class="panel"><h2>Recent errors</h2><div id="errors"></div></div>',
  '  </div>',
  '  <div class="panel">',
  '    <h2>Raw data explorer</h2>',
  '    <div style="margin-bottom:12px;"><select id="sheetPicker" onchange="loadSheet(this.value)"></select></div>',
  '    <div class="tableWrap"><table id="sheetTable"><thead><tr id="sheetHead"></tr></thead><tbody id="sheetBody"></tbody></table></div>',
  '  </div>',
  '</div>'
].join('\n');

var DASHBOARD_JS_ = [
  'function esc(s){ return String(s === undefined || s === null ? "" : s).replace(/&/g,"&amp;").replace(/</g,"&lt;"); }',
  '',
  'function loadAll(){',
  '  google.script.run.withSuccessHandler(render).withFailureHandler(renderError).getDashboardData();',
  '}',
  '',
  'function renderError(err){',
  '  document.getElementById("lastUpdated").textContent = "Error: " + (err && err.message ? err.message : err);',
  '}',
  '',
  'function tile(label, value, cls){',
  '  return \'<div class="tile"><div class="k">\' + esc(label) + \'</div><div class="v \' + (cls||"") + \'">\' + esc(value) + \'</div></div>\';',
  '}',
  '',
  'function render(data){',
  '  document.getElementById("lastUpdated").textContent = "Updated " + new Date(data.generatedAt).toLocaleString();',
  '',
  '  var interested = data.replyBreakdown.interested || 0;',
  '  document.getElementById("tiles").innerHTML = [',
  '    tile("Sourced", data.funnel[0].count),',
  '    tile("Sent", data.funnel[6].count),',
  '    tile("Replied", data.funnel[7].count),',
  '    tile("Interested", interested, "good"),',
  '    tile("Avg ICP fit", data.avgIcpScore),',
  '    tile("Suppressed", data.suppressionCount),',
  '    tile("Errors (24h)", data.errorCount24h, data.errorCount24h > 0 ? "risk" : "")',
  '  ].join("");',
  '',
  '  var maxFunnel = Math.max.apply(null, data.funnel.map(function(f){return f.count;})) || 1;',
  '  document.getElementById("funnel").innerHTML = data.funnel.map(function(f){',
  '    var pct = Math.round((f.count / maxFunnel) * 100);',
  '    return \'<div class="funnelRow"><span>\' + esc(f.stage) + \'</span><div class="bar"><div class="fill" style="width:\' + pct + \'%"></div></div><span class="n">\' + f.count + \'</span></div>\';',
  '  }).join("");',
  '',
  '  document.getElementById("replyBreakdown").innerHTML = renderBreakdown(data.replyBreakdown) || \'<div class="empty">No replies yet.</div>\';',
  '',
  '  document.getElementById("senderStats").innerHTML = data.senderStats.length ? data.senderStats.map(function(s){',
  '    var pct = s.dailyCap ? Math.min(100, Math.round((s.sentToday / s.dailyCap) * 100)) : 0;',
  '    return \'<div class="senderCard"><div class="top"><span>\' + esc(s.sender) + \'</span><span>\' + s.sentToday + \' / \' + s.dailyCap + \' today · \' + s.totalSent + \' all-time</span></div><div class="bar"><div class="fill\' + (pct>=100?" risk":"") + \'" style="width:\' + pct + \'%"></div></div></div>\';',
  '  }).join("") : \'<div class="empty">No SENDER_ACCOUNTS configured.</div>\';',
  '',
  '  document.getElementById("activity").innerHTML = data.recentActivity.length ? data.recentActivity.map(function(a){',
  '    var tagClass = a.type.indexOf("reply_") === 0 ? a.type.replace("reply_","") : "";',
  '    var label = a.type === "sent" ? "sent" : a.type.replace("reply_","reply: ");',
  '    return \'<li><span class="tag \' + tagClass + \'">\' + esc(label) + \'</span>\' + esc(a.detail) + \'<span class="when">\' + new Date(a.at).toLocaleString() + \'</span></li>\';',
  '  }).join("") : \'<li class="empty">Nothing sent or replied to yet.</li>\';',
  '',
  '  document.getElementById("errors").innerHTML = data.recentErrors.length ? data.recentErrors.map(function(e){',
  '    return \'<div class="errorRow"><b>\' + esc(e.function_name) + \'</b> — \' + esc(e.message) + \'<br><span style="opacity:.7">\' + new Date(e.timestamp).toLocaleString() + \'</span></div>\';',
  '  }).join("") : \'<div class="empty">No errors logged. Good sign.</div>\';',
  '}',
  '',
  'function renderBreakdown(obj){',
  '  var keys = Object.keys(obj);',
  '  if (!keys.length) return "";',
  '  var max = Math.max.apply(null, keys.map(function(k){return obj[k];}));',
  '  var cls = { interested: "good", not_interested: "risk", unsubscribe: "risk" };',
  '  return keys.sort(function(a,b){return obj[b]-obj[a];}).map(function(k){',
  '    var pct = Math.round((obj[k] / max) * 100);',
  '    return \'<div class="barRow"><span>\' + esc(k) + \'</span><div class="bar"><div class="fill \' + (cls[k]||"") + \'" style="width:\' + pct + \'%"></div></div><span>\' + obj[k] + \'</span></div>\';',
  '  }).join("");',
  '}',
  '',
  'function loadSheet(name){',
  '  google.script.run.withSuccessHandler(renderSheet).withFailureHandler(renderError).getSheetRows(name, 200);',
  '}',
  '',
  'function renderSheet(data){',
  '  var picker = document.getElementById("sheetPicker");',
  '  if (!picker.options.length) {',
  '    data.sheetNames.forEach(function(name){',
  '      var opt = document.createElement("option"); opt.value = name; opt.textContent = name; picker.appendChild(opt);',
  '    });',
  '    picker.value = "SentLog";',
  '  }',
  '  document.getElementById("sheetHead").innerHTML = data.header.map(function(h){return "<th>"+esc(h)+"</th>";}).join("");',
  '  document.getElementById("sheetBody").innerHTML = data.rows.length ? data.rows.map(function(row){',
  '    return "<tr>" + data.header.map(function(h){return "<td title=\\"" + esc(row[h]) + "\\">" + esc(row[h]) + "</td>";}).join("") + "</tr>";',
  '  }).join("") : \'<tr><td colspan="\' + data.header.length + \'" class="empty">No rows yet.</td></tr>\';',
  '}',
  '',
  'loadAll();',
  'loadSheet("SentLog");',
  'setInterval(loadAll, 60000);'
].join('\n');
